@baseUrl = http://localhost:3000

# PESSOAS
### Criar uma pessoa
POST {{baseUrl}}/pessoas
Content-Type: application/json

{
  "nome": "Joana Dark",
  "email": "joana.dark@example.com",
  "passwordHash": "hashed_password_123"
}

### Listar todas as pessoas
GET {{baseUrl}}/pessoas

### Buscar uma pessoa por ID
GET {{baseUrl}}/pessoas/19

### Atualizar uma pessoa
PATCH {{baseUrl}}/pessoas/19
Content-Type: application/json

{
  "nome": "Joana Dark Atualizada",
  "email": "joana.dark.atualizada@example.com"
}

### Deletar uma pessoa
DELETE {{baseUrl}}/pessoas/16

### Deletar todas as pessoas
DELETE {{baseUrl}}/pessoas/


# RECADOS
### RecadosController

# @name RecadosController

### lista todos os recados
GET {{baseUrl}}/recados/
?limit=2
&offset=0

### lista apenas um recado
GET {{baseUrl}}/recados/15/

### cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
"deId": 19,
"paraId": 18,
"texto": "deId 19 'Joana' paraId 18'Leo'"
  }

### cria um recado (texto automático no backend)
POST {{baseUrl}}/recados/
Content-Type: application/json

{
"texto": "Recado automático",
"deId": 16,
"paraId": 4
}


### atualiza um recado
PATCH {{baseUrl}}/recados/36/
Content-Type: application/json

{
    "texto": "De Joana para Leo: Recado atualizado",
    "lido": true
}

### Apaga um recado
DELETE {{baseUrl}}/recados/71/


### Apaga todos os recados
DELETE {{baseUrl}}/recados/



##############################

# Pessoas

# Pessoas
### PessoasController

# @name PessoasController

### lista todas as pessoas
GET {{baseUrl}}/pessoas/
?limit=10
&offset=10
# &user=luiz


### lista apenas uma pessoa
GET {{baseUrl}}/pessoas/5/

### cria uma pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
  "nome": "Luiedswwz",
  "email": "luizwew@example.ceom",
  "passwordHash": "1e234www56"
}
### cria uma pessoa (senha automática no backend)
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
  "nome": "Luiz dAlberto",
  "email": "ludiz.alberto@example.com",
  "passwordHash": "123d4www56"
}


### atualiza uma pessoa
PATCH {{baseUrl}}/pessoas/9/
Content-Type: application/json

{
    "nome": "Luiz eAlbderto",
    "email": "luiezd.albeerto@eexamdple.coem"
}

### Apaga uma pessoa
DELETE {{baseUrl}}/pessoas/9/

### Apaga todas as pessoas
DELETE {{baseUrl}}/pessoas/

