flowchart LR
  Client[Cliente HTTP] --> Main[src/main.ts bootstrap]
  Main --> NestFactory[NestFactory.create AppModule]
  NestFactory --> AppModule[AppModule]
  Main --> GlobalPipes[useGlobalPipes]
  GlobalPipes --> ValidationPipe[ValidationPipe global]
  ValidationPipe --> Rules[whitelist + forbidNonWhitelisted + transform false]
  GlobalPipes --> ParseIntIdPipeGlobal[ParseIntIdPipe global - valida params id]
  Main --> Listen[app.listen PORT 3000 default]
